name: stitchup
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish the app

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.3
  emoji_picker_flutter: ^4.3.0
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.4.5
  firebase_analytics: ^11.4.5
  firebase_app_check: ^0.3.2+5
  firebase_messaging: ^15.2.5
  photo_manager: ^3.6.4

  # Auth & Social Login
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2

  # Image & File
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_image_compress: ^2.4.0
  pro_image_editor: ^9.4.0
  path_provider: ^2.1.5

  # Location & Maps
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.3
  flutter_google_places_hoc081098: 2.0.0-beta.1
  flutter_google_maps_webservices: ^1.1.1

  # State & Utils
  get: ^4.7.2
  provider: ^6.1.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.3
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  intl: ^0.20.2
  http: ^1.1.0
  app_settings: ^6.1.1
  settings_ui: ^2.0.2
  supabase_flutter: ^2.9.1

  # OTP & Verification
  pin_code_fields: ^8.0.1
  flutter_otp_text_field: ^1.5.1+1
  agora_rtc_engine: ^6.5.2

  # Contacts & Notifications
  flutter_contacts: ^1.1.9+2
  flutter_local_notifications: ^19.1.0

  # Audio
  flutter_sound: ^9.28.0
  file_picker: ^10.1.2
  video_player: ^2.9.5
  signature: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  draggable_widget: ^2.0.0
  flutter_svg: ^2.1.0
  flutter_emoji: ^2.5.1
  video_editor: ^3.0.0
  video_trimmer: ^5.0.0
  firebase_performance: ^0.10.1+5
  flutter_colorpicker: ^1.1.0
  just_audio: ^0.10.2
  path: ^1.9.1
  story_view: ^0.16.5
  flutter_riverpod: ^2.6.1
  share_plus: ^11.0.0
  cloud_functions: ^5.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/stitchup black round.png
    - assets/stitchup round.png
    - assets/flag-7403565_1920.png
    - assets/Login logo.png
    - assets/facebook-2815970_1920.jpg
    - assets/g-logo.png

  fonts:
    - family: PlayfairDisplaySC
      fonts:
        - asset: assets/fonts/Playfair_Display_SC/PlayfairDisplaySC-Regular.ttf

