// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--1GvfeUW3IVxuql0cENhwDugZYWo0Mw',
    appId: '1:551844473887:android:9c9009a019136f28a4f92a',
    messagingSenderId: '551844473887',
    projectId: 'stitchup-d7371',
    storageBucket: 'stitchup-d7371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Ms3KnVP2cjQT8c_RaAXbH8sQnRRjZF0',
    appId: '1:551844473887:ios:2d9263709baec5fda4f92a',
    messagingSenderId: '551844473887',
    projectId: 'stitchup-d7371',
    storageBucket: 'stitchup-d7371.firebasestorage.app',
    androidClientId: '551844473887-g4flil82rk504asv4m999e48ue153o8v.apps.googleusercontent.com',
    iosClientId: '551844473887-9vhvscbmaa3mm313mppv6soo513qujfn.apps.googleusercontent.com',
    iosBundleId: 'com.stitchup.dart',
  );

}